sudo: required

branches:
  only:
    - master

jobs:
  include:

    - stage: test
       name: "Unit Tests"

      language: python
      python: "2.7"
      cache: pip

      install:
        - pip install -r requirements.txt

      script:
        - true
      #  - python tests.py

    - stage: test
      name: "Documentation Tests"
      language: node_js
      node_js: 10

      install:
        - npm install

      script:
        - npm run lint:md
        - npm run lint:text
